global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
    scrape_interval: 5s

  - job_name: 'workers'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['worker:8080']
    scrape_interval: 5s
